INSERT OR IGNORE INTO pages (id, parent_id, title, content_json, sort_order) VALUES
('home', NULL, '🏠 Главное', '[]', 0),
('semester-1', NULL, '1️⃣ 1 семестр', '[]', 10),
('subject-economics', 'semester-1', 'Экономика', '[]', 10),
('subject-culture', 'semester-1', 'Культурология', '[]', 20),
('subject-math-analysis', 'semester-1', 'Математический анализ', '[]', 30),
('subject-pe', 'semester-1', 'Физическая культура', '[]', 40),
('subject-history', 'semester-1', 'История России', '[]', 50),
('subject-linear', 'semester-1', 'Линейная алгебра и геометрия', '[]', 60),
('subject-it', 'semester-1', 'Теоретические основы информатики и ИКТ', '[]', 70),
('subject-language', 'semester-1', 'Иностранный язык', '[]', 80),
('subject-discrete', 'semester-1', 'Дискретная математика', '[]', 90),
('subject-programming', 'semester-1', 'Основы программирования', '[]', 100),
('sessions', NULL, '🎓 Сессии', '[]', 20),
('session-install', 'sessions', 'Установочная сессия', '[]', 10),
('session-exam', 'sessions', 'Экзаменационная сессия', '[]', 20),
('dkr', NULL, '📝 ДКР и задания', '[]', 30),
('teachers', NULL, '👨‍🏫 Преподаватели', '[]', 40),
('materials', NULL, '📎 Материалы', '[]', 50),
('links', NULL, '🔗 Важные ссылки', '[]', 60),
('archive', NULL, '🗃 Архив', '[]', 70);
